# Generated by Django 2.2.5 on 2021-01-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('emial', 'Email'), ('github', 'Github')], default='emial', max_length=50),
        ),
    ]
